spring:
  application:
    name: eureka-service

server:
  port: ${PORT:8330}


######### EUREKA ##############

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
      