server:
  port: ${PORT:8340}

spring:
  application:
    name: db-cliente-server


# eureka config
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:${PORT:8330}/eureka/
  instance:
    hostname: localhost
    
